apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: example-app

resources:
  - ../namespace.yaml
  - ../configmap.yaml
  - ../deployment.yaml
  - ../service.yaml
  - ../ingress.yaml

commonLabels:
  app: example-app
  managed-by: argocd

